name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Deploy via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.YC_HOST }}
        username: ${{ secrets.YC_USER }}
        key: ${{ secrets.YC_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/testinscube"
        overwrite: true
        rm: true 

    - name: Restart app on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.YC_HOST }}
        username: ${{ secrets.YC_USER }}
        key: ${{ secrets.YC_SSH_KEY }}
        script: |
          cd /var/www/testinscube
          npm install
          pm2 restart testinscube
