name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install and build
      run: |
        npm ci
        npm run build
        echo "New BUILD_ID: $(cat .next/BUILD_ID)"

    - name: Secure cleanup (only .next and node_modules)
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.YC_HOST }}
        username: ${{ secrets.YC_USER }}
        key: ${{ secrets.YC_SSH_KEY }}
        script: |
          rm -rf /var/www/testinscube/.next
          rm -rf /var/www/testinscube/node_modules

    - name: Deploy with rsync (точная синхронизация)
      uses: burnett01/rsync-deployments@v5
      with:
        switches: -avz --delete
        path: ./
        remote_path: /var/www/testinscube/
        remote_host: ${{ secrets.YC_HOST }}
        remote_user: ${{ secrets.YC_USER }}
        remote_key: ${{ secrets.YC_SSH_KEY }}
        exclude: |
          .git
          .github
          .gitignore
          README.md

    - name: Install and restart
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.YC_HOST }}
        username: ${{ secrets.YC_USER }}
        key: ${{ secrets.YC_SSH_KEY }}
        script: |
          cd /var/www/testinscube
          npm ci --production
          pm2 delete test-next-app || true
          pm2 start npm --name "test-next-app" -- start
          echo "Active BUILD_ID: $(cat /var/www/testinscube/.next/BUILD_ID)"