name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install and build
      run: |
        npm ci
        npm run build
        echo "New BUILD_ID: $(cat .next/BUILD_ID)"

    - name: Prepare server (safe cleanup)
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.YC_HOST }}
        username: ${{ secrets.YC_USER }}
        key: ${{ secrets.YC_SSH_KEY }}
        script: |
          # Сохраняем .env если существует
          if [ -f "/var/www/testinscube/.env" ]; then
            cp /var/www/testinscube/.env /tmp/env_backup
          fi
          
          # Очищаем только нужные директории
          rm -rf /var/www/testinscube/.next
          rm -rf /var/www/testinscube/node_modules
          mkdir -p /var/www/testinscube/.next

    - name: Deploy files (SCP)
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.YC_HOST }}
        username: ${{ secrets.YC_USER }}
        key: ${{ secrets.YC_SSH_KEY }}
        source: ".next/,public/,package.json,package-lock.json,next.config.js,.env.production"
        target: "/var/www/testinscube"
        overwrite: true
        strip_components: 0

    - name: Restore .env
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.YC_HOST }}
        username: ${{ secrets.YC_USER }}
        key: ${{ secrets.YC_SSH_KEY }}
        script: |
          if [ -f "/tmp/env_backup" ]; then
            mv /tmp/env_backup /var/www/testinscube/.env
            chmod 600 /var/www/testinscube/.env
          fi

    - name: Install and restart
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.YC_HOST }}
        username: ${{ secrets.YC_USER }}
        key: ${{ secrets.YC_SSH_KEY }}
        script: |
          cd /var/www/testinscube
          npm ci --production
          pm2 delete test-next-app || true
          pm2 start npm --name "test-next-app" -- start
          echo "Active BUILD_ID: $(cat /var/www/testinscube/.next/BUILD_ID)"